#include "../include/codegen.h"

#define CODEGEN_ARRAY(f, a, s, t) fprintf(f, "{ "); \
	for (int i = 0; i < s; i++) { \
		fprintf(f, t, a[i]); \
		if (i < s - 1) \
			fprintf(f, ", "); \
		else \
			fprintf(f, " };\n"); \
	}

void codegen_generate(FILE* fp, SaphCore* core, const char* root_path)
{
	fprintf(fp, "// Generated by %s\n", BUILD);
	fprintf(fp, "#include <stdio.h>\n");
	fprintf(fp, "#include \"%s\\include\\vm.h\"\n\n", root_path);

	fprintf(fp, "static uint8_t program[] = ");
	CODEGEN_ARRAY(fp, core->bc->code, core->bc->size, "%d")

	fprintf(fp, "static double constants[] = ");
	CODEGEN_ARRAY(fp, core->bc->constants, core->bc->const_size, "%f")

	fprintf(fp, "\nint main(void)\n");
	fprintf(fp, "{\n");
	fprintf(fp, "\tVM* vm = vm_create(program, constants);\n");
	fprintf(fp, "\tvm_run(vm);\n");
	fprintf(fp, "\tgetchar();\n\n");
	fprintf(fp, "\treturn 0;\n");
	fprintf(fp, "}\n");
}
